/** Category Actions */
export const CHANGE_CATEGORY = "CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS"

/**Products Actions */
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";

/**Pagination Actions */
export const CHANGE_PAGE = "CHANGE_PAGE"
export const CHANGE_PAGEPERCOUNT = "CHANGE_PAGEPERCOUNT"


/** Cart Actions */

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

